###############################################################
#                   Authelia configuration                    #
###############################################################

host: 0.0.0.0
port: 9091
log_level: debug
# This secret can also be set using the env variables AUTHELIA_JWT_SECRET_FILE
jwt_secret: $AUTHELIA_JWT_SECRET_FILE
default_redirection_url: https://auth.smanson.duckdns.org
totp:
  issuer: authelia.com
  period: 30
  skew: 1

duo_api:
  hostname: api-6074a2cb.duosecurity.com
  integration_key: DIJTIW6ALAR156Y7QONC
  # This secret can also be set using the env variables AUTHELIA_DUO_API_SECRET_KEY_FILE
  secret_key: ZOCttoKqqUcTxhVGcHjYO7HykGCYUO4suMAIpuPM

authentication_backend:
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 1024
access_control:
  default_policy: deny
  rules:
    # Rules applied to everyone
    - domain: auth.smanson.duckdns.org
      policy: bypass
#    - domain: traefik.smanson.duckdns.org
#      policy: two_factor
#    - domain: sonarr.smanson.duckdns.org
#      policy: two_factor
    - domain: "*.smanson.duckdns.org"
      policy: two_factor
    - domain: "smanson.duckdns.org"
      policy: two_factor
session:
  name: authelia_session

  # This secret can also be set using the env variables AUTHELIA_SESSION_SECRET_FILE
  secret: $AUTHELIA_SESSION_SECRET_FILE
  expiration: 3600 # 1 hour
  inactivity: 300 # 5 minutes
  domain: smanson.duckdns.org # Should match whatever your root protected domain is

  redis:
    host: redis
    port: 6379 
    # This secret can also be set using the env variables AUTHELIA_SESSION_REDIS_PASSWORD_FILE
    # password: $AUTHELIA_SESSION_REDIS_PASSWORD_FILE

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
#  local:
#    path: /config/db.sqlite3
  mysql:
  # MySQL allows running multiple authelia instances. Create database and enter details below.
    host: mariadb
    port: 3306
    database: authelia
    username: plex-server
    # Password can also be set using a secret: https://docs.authelia.com/configuration/secrets.html
    password: ramona123
#notifier:
  smtp:
    username: plex@smanson.co.za
    # This secret can also be set using the env variables AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE
    password: tXe43fFX!PYg@M&
    host: smtp.gmail.com
    port: 587
    sender: plex@smanson.co.za
