global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  
  external_labels:
      monitor: 'my-project'

scrape_configs:

  - job_name: 'prometheus'
    scheme: http
    scrape_interval: 5s
    static_configs:
         - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    scheme: http
    scrape_interval: 5s
    static_configs:
         - targets: ['cadvisor:8080']

  - job_name: 'node-exporter'
    scheme: http
    scrape_interval: 5s
    static_configs:
         - targets: ['node-exporter:9100']

  - job_name: 'traefik'
    scheme: http
    scrape_interval: 5s
    static_configs:
         - targets: ['traefik:8082']

  - job_name: 'grafana'
    scheme: http
    scrape_interval: 5s
    static_configs:
      - targets: ['grafana:3000']
